{
 "title": "Redis endpoint dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(push_time_seconds, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Migrated processed total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum({mtype=\"suc\", job=~\"$job\"}) + sum({mtype=\"err\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Migrated success total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum({mtype=\"suc\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Migrated failure total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum({mtype=\"err\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Migrated success count per endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort({mtype=\"suc\", job=~\"$job\"})",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Migrated failure count per endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort({mtype=\"err\", job=~\"$job\"})",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}