{
 "title": "redis memory dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Instance",
    "query": "label_values(push_time_seconds{type=\"memory\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum({job=~\"$job\", mtype=\"db_size\"})"
    }
   ]
  },
  {
   "title": "Expired count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum({job=~\"$job\", mtype=\"db_expire\"})"
    }
   ]
  },
  {
   "title": "Memory usage histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_usage_histogram{job=~\"$job\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Count by db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{job=~\"$job\", mtype=\"db_size\"}",
     "legendFormat": "{{dbnum}}"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "key_mem_total{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory usage by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort({mtype=\"mem\", job=~\"$job\"})",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Count by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort({mtype=\"count\", job=~\"$job\"})",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Expired by db",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{job=~\"$job\", mtype=\"db_expire\"}",
     "legendFormat": "{{dbnum}}"
    }
   ]
  },
  {
   "title": "Largest key table(desc)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc({mtype=\"key\", job=~\"$job\"})"
    }
   ]
  }
 ]
}