{
 "title": "cluster",
 "tags": [ "cluster" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": "select \"property0\",value from cluster_monitor where $timeFilter;"
   }
  ]
 },
 "panels": [
  { "title": "base info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster redis version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "redis_version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster up in seconds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "uptime_in_seconds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "known nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_known_nodes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "master nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "$tag_property0:$tag_property2 fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "property2" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_node_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "$tag_property0:$tag_property2 pfail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "property2" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_node_pfail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "cluster slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "assigned",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_slot_assigned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "ok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_slot_ok",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_slot_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "pfail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_slot_pfail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_node_slot",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster protocol messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_stats_messages_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_stats_messages_sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "cluster status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cluster_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "cluster current epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cluster_current_epoch",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  { "title": "monitor info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "cluster key count info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_property0:count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbnum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "property3", "operator": "=", "value": "db0" }
     ]
    },
    {
     "alias": "total key count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbnum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "property3", "operator": "=", "value": "db0" }
     ]
    }
   ]
  },
  {
   "title": "cluster key expired info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_property0:expiring",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbexp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "property3", "operator": "=", "value": "db0" }
     ]
    },
    {
     "alias": "total expiring keys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbexp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" },
      { "condition": "AND", "key": "property3", "operator": "=", "value": "db0" }
     ]
    },
    {
     "alias": "expired keys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "expired_keys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "evicted keys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "evicted_keys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster hit rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "keyspace_hit_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster clients info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_property0:connected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connected_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "total connected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connected_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "max clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maxclients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "total blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocked_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "total tracking",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tracking_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "total received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_connections_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster memory info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "total system memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_system_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "$tag_property0:used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster cpu info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_property0:sys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_sys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "$tag_property0:user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster net info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_property0:inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_input_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "$tag_property0:outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_output_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_output_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_input_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster ops info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_commands_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "read ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_reads_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "write ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_writes_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster fragment bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem_fragmentation_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster fragment rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem_fragmentation_ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster command info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "command processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_commands_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "read processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_reads_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "write processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_writes_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "error replied",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_error_replies",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    },
    {
     "alias": "slow processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_slow_log",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "cluster slow log latency info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_property0:latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slow_log_latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=", "value": "master" }
     ]
    }
   ]
  }
 ]
}