{
 "title": "endpoint",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "show tag values with key = \"instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "success mean count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "success",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"success\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "failure mean count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "failure",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"failure\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "send mean count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "send",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"send\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "reconnect target mean count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_facade",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reconnect",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"reconnect\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}