{
 "title": "memory",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "show tag values with key = \"instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "total count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"dbnum\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbnum_*/" }
     ]
    }
   ]
  },
  {
   "title": "expired count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"dbexp\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbexp_*/" }
     ]
    }
   ]
  },
  {
   "title": "count by db",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"dbnum\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbnum_*/" }
     ]
    }
   ]
  },
  {
   "title": "expired by db",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"dbexp\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbexp_*/" }
     ]
    }
   ]
  },
  {
   "title": "total memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT last(\"value\") FROM \"30days\".\"total_memory\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=", "value": "total_memory" }
     ]
    }
   ]
  },
  {
   "title": "count by type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property0" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "type_count",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"type_count\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "memory usage by type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_property0",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"type_memory\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY \"property0\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "COUNTER" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^memory_*/" }
     ]
    }
   ]
  },
  {
   "title": "top N keys",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "big_key",
     "query": "SELECT \"property0\" as \"key name\", \"property1\" as \"key type\", \"property2\" as \"db\", \"property3\" as \"elements in key\",\"value\" as \"size\" FROM \"30days\".\"big_key\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}