{
 "title": "monitor",
 "tags": [ "details" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": "show tag values from monitor with key = \"property1\""
   },
   {
    "name": "role",
    "label": "role",
    "query": "show tag values from monitor with key = \"property2\" where \"property1\" = '$name';"
   },
   {
    "name": "host",
    "label": "host",
    "query": "show tag values from monitor with key = \"property0\" where \"property1\" = '$name' and \"property2\" = '$role'"
   }
  ]
 },
 "panels": [
  { "title": "base info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "redis version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "redis_version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "redis_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "role",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "uptime in seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "uptime_in_seconds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "total connections received",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "total_connections_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "total commands processed",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "total_commands_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "total net input bytes",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "total_net_input_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "total net output bytes",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "total_net_output_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  { "title": "monitor info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "count info per db",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_property3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property3" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbnum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbnum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property3", "operator": "=~", "value": "/^db.*/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "expires info per db",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_property3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "property3" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbexp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dbexp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property3", "operator": "=~", "value": "/^db.*/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "expired key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "expired_keys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "evicted key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "evicted_keys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "hit rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "hit rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "keyspace_hit_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "client info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "connected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connected_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_connections_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blocked_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maxclients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "memory info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "used memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "max memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maxmemory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used memory lua",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_lua",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used memory dataset",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_dataset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used memory script",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_scripts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "used memory function",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_functions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used memory rss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_rss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used memory peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_memory_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "cpu info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "used cpu sys",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_sys",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used cpu user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used cpu sys children",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_sys_children",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "used cpu user children",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "used_cpu_user_children",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "net info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_input_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_net_output_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "ops info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "instantaneous_ops_per_sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "write ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "instantaneous_write_ops_per_sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "read ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "instantaneous_read_ops_per_sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "other ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "instantaneous_other_ops_per_sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "evicted keys ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "evicted_keys_per_sec",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "slow log ops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_slow_log",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "fragment byte",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "memory fragment",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem_fragmentation_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "fragment rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "memory fragment rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem_fragmentation_ratio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "command info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "command processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_commands_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "read processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_reads_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "write processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_writes_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "error replied",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_error_replies",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "alias": "slow processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total_slow_log",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "slow log latency info",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slow_log_latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  { "title": "slow log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "slow log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "limit": "128",
     "measurement": "slow_log",
     "select": [
      [
       { "params": [ "property3" ], "type": "field" },
       { "params": [ "id" ], "type": "alias" }
      ],
      [
       { "params": [ "property4" ], "type": "field" },
       { "params": [ "timestamp" ], "type": "alias" }
      ],
      [
       { "params": [ "property6" ], "type": "field" },
       { "params": [ "client" ], "type": "alias" }
      ],
      [
       { "params": [ "property7" ], "type": "field" },
       { "params": [ "ip address" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "execution time" ], "type": "alias" }
      ],
      [
       { "params": [ "property5" ], "type": "field" },
       { "params": [ "command" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "property0", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "property1", "operator": "=~", "value": "/^$name$/" },
      { "condition": "AND", "key": "property2", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  }
 ]
}