name: Native Image

on: [push]

jobs:
  build:
    name: Build Native Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '11'
          version: 'latest'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven Build
        run:
          mvn clean install -Pstatic -DskipTests
